### ISSUE TITLE
Create Jackpot Command

### ISSUE THREAD

**Issue by NelsonJTSM** [Flaremaker/Danny-Bot#3]
Register a slash command for the jackpot command. For an example on how to do it, look at [this](https://github.com/Flaremaker/Danny-Bot/blob/11e10e0e76ca9a3170ae04eafb33e64e4a19eab7/index.js#L9-L12).

Once registered, create a response to the slash command that generates 3 random numbers, and if they're the same, you win. Here is an example on how to create the [response](https://github.com/Flaremaker/Danny-Bot/blob/11e10e0e76ca9a3170ae04eafb33e64e4a19eab7/index.js#L18-L20). Feel free to write the code in a separate file, then import the function into ```index.js```.

**Comment by Flaremaker** [comment]
YO i can fix this issue i just need to test my code how do you run javascript code

**Comment by NelsonJTSM** [comment]
> YO i can fix this issue i just need to test my code how do you run javascript code 

You run the project by running npm start

**Comment by Flaremaker** [comment]
I have registered a slash command that generates three random numbers
